bpmns:
  tenants:
    - id: "rhino"
      flows:
        payment-transfer: "minimal_mock_fund_transfer-{dfspid}"
    - id: "lion"
      flows:
        payment-transfer: "MockPayerFundTransfer-{dfspid}"
    - id: "gorilla"
      flows:
        payment-transfer: "PayerFundTransfer-{dfspid}"
        outbound-transfer-request: "mpesa_flow_{ams}-{dfspid}"
